model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.latent_diffclip.LatentDiffusionCLIP
  params:
    # ckpt_path: <CKPT_DIR>/epoch=000025-val_loss_ema=0.110.ckpt
    linear_start: 0.0015
    linear_end: 0.0205
    num_timesteps_cond: 1
    timesteps: 1000
    first_stage_key: latent
    cond_stage_key: null
    image_size: 32
    channels: 3
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val_loss
    
    edit_attr: happy
    strength: 0.5
    num_train_steps: 6
    num_test_steps: 40
    eta: 0.0
    cls_loss_w: 0.0
    clip_loss_w: 1.0
    id_loss_w: 1.0
    l2_loss_w: 1.0
    cls_model_name: 'enet_b2_7'
    clip_model_name: 'ViT-B/16'
    unconditional_guidance_scale: 1.0
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 3
        out_channels: 3
        model_channels: 160
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 32 for f4
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 16384
        # ckpt_path: <CKPT_DIR>/epoch=000005-val_rec_loss_epoch=0.138-val_aeloss_epoch=0.151.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 128
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 32
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
          
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder3
      params:
        embed_dim: 512
        n_classes: 8
        key: class_label
        p_uncond: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    train:
      target: ldm.data.latents.LatentTrain
      params:
        # Precompute and replace accordingly
        # training_precomputed_latents_path: /gpu-data2/jpik/latent-diffusion/samples/precomputed/precomputed_noema_train_xlat_nsamples4000_ddim40_eta0.0_scale1.0_strength0.5_affectnet-v5-128-ldm-vq-f4_epoch=000025-val_loss_ema=0.110.npy 
        # training_origin_path: /gpu-data2/jpik/latent-diffusion/samples/precomputed/precomputed_noema_train_x0_nsamples4000_ddim40_eta0.0_scale1.0_strength0.5_affectnet-v5-128-ldm-vq-f4_epoch=000025-val_loss_ema=0.110.npy
        # training_files_path: /gpu-data2/jpik/latent-diffusion/samples/precomputed/precomputed_noema_train_fp_nsamples4000_ddim40_eta0.0_scale1.0_strength0.5_affectnet-v5-128-ldm-vq-f4_epoch=000025-val_loss_ema=0.110.npy
        n_samples: 1000
        size: 128
    validation:
      target: ldm.data.latents.LatentTest
      params:
        # Precompute and replace accordingly
        # test_precomputed_latents_path: /gpu-data2/jpik/latent-diffusion/samples/precomputed/precomputed_noema_test_xlat_nsamples4000_ddim40_eta0.0_scale1.0_strength0.5_affectnet-v5-128-ldm-vq-f4_epoch=000025-val_loss_ema=0.110.npy
        # test_origin_path: /gpu-data2/jpik/latent-diffusion/samples/precomputed/precomputed_noema_test_x0_nsamples4000_ddim40_eta0.0_scale1.0_strength0.5_affectnet-v5-128-ldm-vq-f4_epoch=000025-val_loss_ema=0.110.npy
        # test_files_path: /gpu-data2/jpik/latent-diffusion/samples/precomputed/precomputed_noema_test_fp_nsamples4000_ddim40_eta0.0_scale1.0_strength0.5_affectnet-v5-128-ldm-vq-f4_epoch=000025-val_loss_ema=0.110.npy
        n_samples: 100
        size: 128

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 100
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    max_epochs: 20